# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.7.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/victortersmitten/Gitprojects/Detectors

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/victortersmitten/Gitprojects/Detectors

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.7.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/victortersmitten/Gitprojects/Detectors/CMakeFiles /Users/victortersmitten/Gitprojects/Detectors/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/victortersmitten/Gitprojects/Detectors/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

HarrisPC.o: HarrisPC.cpp.o

.PHONY : HarrisPC.o

# target to build an object file
HarrisPC.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/HarrisPC.cpp.o
.PHONY : HarrisPC.cpp.o

HarrisPC.i: HarrisPC.cpp.i

.PHONY : HarrisPC.i

# target to preprocess a source file
HarrisPC.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/HarrisPC.cpp.i
.PHONY : HarrisPC.cpp.i

HarrisPC.s: HarrisPC.cpp.s

.PHONY : HarrisPC.s

# target to generate assembly for a file
HarrisPC.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/HarrisPC.cpp.s
.PHONY : HarrisPC.cpp.s

NaiveGaussianHOGPC.o: NaiveGaussianHOGPC.cpp.o

.PHONY : NaiveGaussianHOGPC.o

# target to build an object file
NaiveGaussianHOGPC.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NaiveGaussianHOGPC.cpp.o
.PHONY : NaiveGaussianHOGPC.cpp.o

NaiveGaussianHOGPC.i: NaiveGaussianHOGPC.cpp.i

.PHONY : NaiveGaussianHOGPC.i

# target to preprocess a source file
NaiveGaussianHOGPC.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NaiveGaussianHOGPC.cpp.i
.PHONY : NaiveGaussianHOGPC.cpp.i

NaiveGaussianHOGPC.s: NaiveGaussianHOGPC.cpp.s

.PHONY : NaiveGaussianHOGPC.s

# target to generate assembly for a file
NaiveGaussianHOGPC.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/NaiveGaussianHOGPC.cpp.s
.PHONY : NaiveGaussianHOGPC.cpp.s

ParkingClassifier.o: ParkingClassifier.cpp.o

.PHONY : ParkingClassifier.o

# target to build an object file
ParkingClassifier.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ParkingClassifier.cpp.o
.PHONY : ParkingClassifier.cpp.o

ParkingClassifier.i: ParkingClassifier.cpp.i

.PHONY : ParkingClassifier.i

# target to preprocess a source file
ParkingClassifier.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ParkingClassifier.cpp.i
.PHONY : ParkingClassifier.cpp.i

ParkingClassifier.s: ParkingClassifier.cpp.s

.PHONY : ParkingClassifier.s

# target to generate assembly for a file
ParkingClassifier.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ParkingClassifier.cpp.s
.PHONY : ParkingClassifier.cpp.s

ParkingDatasetDescription.o: ParkingDatasetDescription.cpp.o

.PHONY : ParkingDatasetDescription.o

# target to build an object file
ParkingDatasetDescription.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ParkingDatasetDescription.cpp.o
.PHONY : ParkingDatasetDescription.cpp.o

ParkingDatasetDescription.i: ParkingDatasetDescription.cpp.i

.PHONY : ParkingDatasetDescription.i

# target to preprocess a source file
ParkingDatasetDescription.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ParkingDatasetDescription.cpp.i
.PHONY : ParkingDatasetDescription.cpp.i

ParkingDatasetDescription.s: ParkingDatasetDescription.cpp.s

.PHONY : ParkingDatasetDescription.s

# target to generate assembly for a file
ParkingDatasetDescription.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ParkingDatasetDescription.cpp.s
.PHONY : ParkingDatasetDescription.cpp.s

Parkplatz.o: Parkplatz.cpp.o

.PHONY : Parkplatz.o

# target to build an object file
Parkplatz.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Parkplatz.cpp.o
.PHONY : Parkplatz.cpp.o

Parkplatz.i: Parkplatz.cpp.i

.PHONY : Parkplatz.i

# target to preprocess a source file
Parkplatz.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Parkplatz.cpp.i
.PHONY : Parkplatz.cpp.i

Parkplatz.s: Parkplatz.cpp.s

.PHONY : Parkplatz.s

# target to generate assembly for a file
Parkplatz.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Parkplatz.cpp.s
.PHONY : Parkplatz.cpp.s

SVMParkingClassifier.o: SVMParkingClassifier.cpp.o

.PHONY : SVMParkingClassifier.o

# target to build an object file
SVMParkingClassifier.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/SVMParkingClassifier.cpp.o
.PHONY : SVMParkingClassifier.cpp.o

SVMParkingClassifier.i: SVMParkingClassifier.cpp.i

.PHONY : SVMParkingClassifier.i

# target to preprocess a source file
SVMParkingClassifier.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/SVMParkingClassifier.cpp.i
.PHONY : SVMParkingClassifier.cpp.i

SVMParkingClassifier.s: SVMParkingClassifier.cpp.s

.PHONY : SVMParkingClassifier.s

# target to generate assembly for a file
SVMParkingClassifier.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/SVMParkingClassifier.cpp.s
.PHONY : SVMParkingClassifier.cpp.s

image_alg.o: image_alg.cpp.o

.PHONY : image_alg.o

# target to build an object file
image_alg.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/image_alg.cpp.o
.PHONY : image_alg.cpp.o

image_alg.i: image_alg.cpp.i

.PHONY : image_alg.i

# target to preprocess a source file
image_alg.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/image_alg.cpp.i
.PHONY : image_alg.cpp.i

image_alg.s: image_alg.cpp.s

.PHONY : image_alg.s

# target to generate assembly for a file
image_alg.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/image_alg.cpp.s
.PHONY : image_alg.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

util.o: util.cpp.o

.PHONY : util.o

# target to build an object file
util.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/util.cpp.o
.PHONY : util.cpp.o

util.i: util.cpp.i

.PHONY : util.i

# target to preprocess a source file
util.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/util.cpp.i
.PHONY : util.cpp.i

util.s: util.cpp.s

.PHONY : util.s

# target to generate assembly for a file
util.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/util.cpp.s
.PHONY : util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... HarrisPC.o"
	@echo "... HarrisPC.i"
	@echo "... HarrisPC.s"
	@echo "... NaiveGaussianHOGPC.o"
	@echo "... NaiveGaussianHOGPC.i"
	@echo "... NaiveGaussianHOGPC.s"
	@echo "... ParkingClassifier.o"
	@echo "... ParkingClassifier.i"
	@echo "... ParkingClassifier.s"
	@echo "... ParkingDatasetDescription.o"
	@echo "... ParkingDatasetDescription.i"
	@echo "... ParkingDatasetDescription.s"
	@echo "... Parkplatz.o"
	@echo "... Parkplatz.i"
	@echo "... Parkplatz.s"
	@echo "... SVMParkingClassifier.o"
	@echo "... SVMParkingClassifier.i"
	@echo "... SVMParkingClassifier.s"
	@echo "... image_alg.o"
	@echo "... image_alg.i"
	@echo "... image_alg.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

